[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
boardo_contract = "AJsNVAr3m5wGLwY9bALRDsX9zeg9VvDJNCAHnpgUwpoc"

[programs.testnet]
boardo_contract = "AJsNVAr3m5wGLwY9bALRDsX9zeg9VvDJNCAHnpgUwpoc"

[programs.devnet]
boardo_contract = "AJsNVAr3m5wGLwY9bALRDsX9zeg9VvDJNCAHnpgUwpoc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.gorbagana.wtf/"
wallet = "~/.config/solana/bdvers.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
